### ISSUE TITLE
Initiative tracking as a list, updated with a "next" button

### ISSUE THREAD

**Issue by margauxdivernois** [margauxdivernois/initiative-tracker#2]
- [x] Have the current player tracked for the fight
- [x] Update the current player with the next button 
- [x] Display the current player differently 
- [x] Keep track of the turn count and display it
